import { type Reference } from "./schemas";
const entries = [
  [
    "nova",
    "Project management dashboard",
    "Dashboard",
    ["Developer", "Dark"],
    "Dense",
    "Thin dividers give a dense issue list room to breathe.",
  ],
  [
    "atelier",
    "Architectural studio homepage",
    "Portfolio",
    ["Editorial", "Minimal"],
    "Sparse",
    "I like the restrained serif hierarchy and the generous image area.",
  ],
  [
    "forma",
    "Minimal ecommerce",
    "E-commerce",
    ["Minimal", "Light"],
    "Balanced",
    "Product photography carries the page. The controls stay quiet.",
  ],
  [
    "stackkit",
    "Developer documentation",
    "Other",
    ["Developer", "Dark"],
    "Dense",
    "Clear navigation and readable code without decorative containers.",
  ],
  [
    "roam",
    "Travel editorial",
    "Blog",
    ["Editorial", "Colorful"],
    "Sparse",
    "Photography leads; a short headline establishes the hierarchy.",
  ],
  [
    "daylight",
    "Calendar application",
    "Dashboard",
    ["Minimal", "Light"],
    "Dense",
    "Soft event colors communicate categories without heavy borders.",
  ],
  [
    "array",
    "Analytics dashboard",
    "Analytics",
    ["Minimal", "Swiss"],
    "Balanced",
    "Flat data presentation with strong alignment.",
  ],
  [
    "lanapark",
    "Portfolio homepage",
    "Portfolio",
    ["Editorial", "Minimal"],
    "Sparse",
    "The typography feels considered without overwhelming the work.",
  ],
] as const;
export const sampleReferences: Reference[] = entries.map(
  ([id, name, category, styles, density, likes], i) => ({
    id,
    name,
    category,
    styles: [...styles],
    density,
    likes,
    notes: "Generated sample reference. Use it to explore the library.",
    url: "",
    screenshot: `/references/${id}.png`,
    tags: [...styles.map((s) => s.toLowerCase()), category.toLowerCase()],
    sample: true,
    createdAt: `2026-09-${String(23 - Math.floor(i / 2)).padStart(2, "0")}T09:00:00.000Z`,
    updatedAt: "2026-09-23T09:00:00.000Z",
  }),
);
